# Generated by Django 5.0.1 on 2024-01-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='breed',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
